title: Karan Anchan
email: kar.anchan02@gmail.com
description: >-
  Master's Student in Computer Science specializing in Artificial Intelligence, 
  Generative AI, and Data Science.
baseurl: ""
url: "https://KaranAnchan.github.io"
twitter_username: 
github_username:  KaranAnchan
linkedin_username: karan-anchan

# Build settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# This sets your GitHub profile pic as the website logo & favicon
logo: https://github.com/KaranAnchan.png
icon: https://github.com/KaranAnchan.png

author:
  name: Karan Anchan
  email: kar.anchan02@gmail.com

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
