title: Karan Anchan
email: kar.anchan02@gmail.com
description: >- # this means to ignore newlines in the description
  Master's Student in Computer Science specializing in Artificial Intelligence, 
  Generative AI, and Data Science at the University of Freiburg.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://KaranAnchan.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  KaranAnchan
linkedin_username: karan-anchan

# Build settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Footer / Contact Info settings
author:
  name: Karan Anchan
  email: kar.anchan02@gmail.com

# Exclude from processing.
# The following items will not be processed, by default.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
